name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Verify
    uses: maveniverse/parent/.github/workflows/ci.yml@main
    with:
      maven-single-run: false
      jdk-matrix: '[ "21", "8" ]'
      maven-test: './mvnw clean verify -e -B -V'
