name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Verify
    uses: maveniverse/parent/.github/workflows/ci.yml@604eaeebdf21d187ae76b5554586c51f204c3575
    with:
      maven-single-run: false
      jdk-matrix: '[ "11", "21" ]'
      maven-test: './mvnw clean verify -e -B -V'
